"""Verify the Section 6 analysis artifacts and their source links."""
from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
PACKAGE = HERE.parents[1]
OUT = PACKAGE / "results" / "p6"
FIGURES = PACKAGE / "figures" / "p6"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as stream:
        return list(csv.DictReader(stream))


def check_png(path: Path) -> None:
    data = path.read_bytes()
    if len(data) < 1000 or data[:8] != b"\x89PNG\r\n\x1a\n":
        raise AssertionError(f"invalid or empty PNG: {path}")


def main() -> None:
    summary_path = OUT / "p6_summary.json"
    summary = json.loads(summary_path.read_text(encoding="utf-8"))

    required_csv = [
        "p6_convergence.csv",
        "p6_balance.csv",
        "p6_physical_checks.csv",
        "p6_sensitivity.csv",
        "p6_scenarios.csv",
    ]
    for name in required_csv:
        path = OUT / name
        if not path.exists():
            raise AssertionError(f"missing CSV: {path}")
        if not read_csv(path):
            raise AssertionError(f"empty CSV: {path}")

    figures = [FIGURES / Path(relative).name for relative in summary["generated_files"]["figures"]]
    for path in figures:
        if not path.exists():
            raise AssertionError(f"missing figure: {path}")
        check_png(path)

    for relative, expected in summary["source_hashes"].items():
        actual = sha256(PACKAGE / relative)
        if actual != expected:
            raise AssertionError(f"source changed after p6 generation: {relative}")

    q2_sensitivity = json.loads(
        (PACKAGE / "results" / "q2" / "q2_parameter_sensitivity.json").read_text(encoding="utf-8")
    )
    for relative, expected in q2_sensitivity["source_sha256"].items():
        if sha256(PACKAGE / relative) != expected:
            raise AssertionError(f"q2 sensitivity source mismatch: {relative}")

    q3 = json.loads(
        (PACKAGE / "results" / "q3" / "q3_validation.json").read_text(encoding="utf-8")
    )
    if sha256(PACKAGE / "code/q2/solve_q2.py") != q3["q2_code_sha256"]:
        raise AssertionError("q3 validation was not generated by the current q2 solver")

    q3_event = float(q3["event_h"])
    q4 = json.loads(
        (PACKAGE / "results" / "q4" / "q4_validation.json").read_text(encoding="utf-8")
    )
    q4_event = float(q4["event_h"])
    main_results = summary["main_results"]
    if abs(float(main_results["q3_event_h"]) - q3_event) > 1e-12:
        raise AssertionError("p6 summary does not match q3 event result")
    if abs(float(main_results["q4_event_h"]) - q4_event) > 1e-12:
        raise AssertionError("p6 summary does not match q4 event result")

    convergence_rows = read_csv(OUT / "p6_convergence.csv")
    sensitivity_rows = read_csv(OUT / "p6_sensitivity.csv")
    scenario_rows = read_csv(OUT / "p6_scenarios.csv")
    physical_rows = read_csv(OUT / "p6_physical_checks.csv")
    if len(convergence_rows) != 17:
        raise AssertionError("unexpected convergence row count")
    if len(sensitivity_rows) != 38:
        raise AssertionError("unexpected sensitivity row count")
    if len(scenario_rows) != 6:
        raise AssertionError("unexpected scenario row count")
    if len(physical_rows) != 4 or any(row["center_is_wettest"] != "True" for row in physical_rows):
        raise AssertionError("physical range checks are incomplete")

    forbidden = [
        path for path in OUT.rglob("*")
        if path.is_file() and path.suffix.lower() in {".md", ".png", ".jpg", ".jpeg"}
    ]
    if forbidden:
        raise AssertionError(f"presentation files leaked into results/p6: {forbidden}")

    print(json.dumps({
        "passed": True,
        "convergence_rows": len(convergence_rows),
        "sensitivity_rows": len(sensitivity_rows),
        "scenario_rows": len(scenario_rows),
        "physical_rows": len(physical_rows),
        "figures": [path.relative_to(PACKAGE).as_posix() for path in figures],
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
