"""Verify the three Section 6 table artifacts and their source links."""
from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
PACKAGE = HERE.parents[1]
OUT = PACKAGE / "results" / "p6"
FIGURES = PACKAGE / "figures" / "p6"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as stream:
        return list(csv.DictReader(stream))


def main() -> None:
    summary_path = OUT / "p6_summary.json"
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    expected_categories = [
        "数值收敛性误差",
        "参数敏感性误差",
        "系统误差：长期边界扰动",
    ]
    if summary["error_categories"] != expected_categories:
        raise AssertionError("Section 6 does not contain exactly the three requested error categories")

    required_csv = [
        "p6_convergence.csv",
        "p6_sensitivity.csv",
        "p6_systematic_boundary.csv",
    ]
    for name in required_csv:
        path = OUT / name
        if not path.exists():
            raise AssertionError(f"missing table: {path}")
        if not read_csv(path):
            raise AssertionError(f"empty table: {path}")

    allowed_result_files = set(required_csv + ["p6_summary.json"])
    actual_result_files = {path.name for path in OUT.iterdir() if path.is_file()}
    if actual_result_files != allowed_result_files:
        raise AssertionError(
            f"unexpected Section 6 result files: {sorted(actual_result_files - allowed_result_files)}"
        )
    if FIGURES.exists() and any(path.is_file() for path in FIGURES.rglob("*")):
        raise AssertionError("Section 6 figures are present although the output is table-only")

    for relative, expected in summary["source_hashes"].items():
        if sha256(PACKAGE / relative) != expected:
            raise AssertionError(f"source changed after p6 generation: {relative}")

    q2_sensitivity = json.loads(
        (PACKAGE / "results" / "q2" / "q2_parameter_sensitivity.json").read_text(encoding="utf-8")
    )
    for relative, expected in q2_sensitivity["source_sha256"].items():
        if sha256(PACKAGE / relative) != expected:
            raise AssertionError(f"q2 sensitivity source mismatch: {relative}")

    q3 = json.loads(
        (PACKAGE / "results" / "q3" / "q3_validation.json").read_text(encoding="utf-8")
    )
    q4 = json.loads(
        (PACKAGE / "results" / "q4" / "q4_validation.json").read_text(encoding="utf-8")
    )
    if sha256(PACKAGE / "code/q2/solve_q2.py") != q3["q2_code_sha256"]:
        raise AssertionError("q3 validation was not generated by the current q2 solver")
    if abs(float(summary["main_results"]["q3_event_h"]) - float(q3["event_h"])) > 1e-12:
        raise AssertionError("p6 summary does not match q3 event result")
    if abs(float(summary["main_results"]["q4_event_h"]) - float(q4["event_h"])) > 1e-12:
        raise AssertionError("p6 summary does not match q4 event result")

    convergence_rows = read_csv(OUT / "p6_convergence.csv")
    sensitivity_rows = read_csv(OUT / "p6_sensitivity.csv")
    systematic_rows = read_csv(OUT / "p6_systematic_boundary.csv")
    if len(convergence_rows) != 17:
        raise AssertionError("unexpected convergence row count")
    if len(sensitivity_rows) != 38:
        raise AssertionError("unexpected sensitivity row count")
    expected_systematic_rows = 2 + 2 * summary["systematic_boundary"]["sample_count"]
    if len(systematic_rows) != expected_systematic_rows:
        raise AssertionError("unexpected systematic-boundary row count")
    if sum(row["sample"] == "mean_baseline" for row in systematic_rows) != 2:
        raise AssertionError("missing mean baselines")
    if sum(row["sample"].startswith("bootstrap_") for row in systematic_rows) != 2 * summary["systematic_boundary"]["sample_count"]:
        raise AssertionError("missing boundary fluctuation samples")
    if any(float(row["residual_std_T_C"]) < 0 or float(row["residual_std_C_kg_per_kg"]) < 0 for row in systematic_rows):
        raise AssertionError("invalid residual scale")

    print(json.dumps({
        "passed": True,
        "convergence_rows": len(convergence_rows),
        "sensitivity_rows": len(sensitivity_rows),
        "systematic_boundary_rows": len(systematic_rows),
        "systematic_samples_per_question": summary["systematic_boundary"]["sample_count"],
        "figures": 0,
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
