"""Canonical names for artifacts generated by the integrated submission code.

The input attachments and workbook templates keep their original names.  This
module only names generated numerical outputs, diagnostics, and figures so
every solver and checker uses the same contract.
"""
from __future__ import annotations

from pathlib import Path


ARTIFACT_NAMES = {
    "q1": {
        "workbook": "result1.xlsx",
        "result_data": "q1_result_data.json",
        "full_precision": "q1_result_full_precision.npz",
        "validation": "q1_validation.json",
        "boundary_cv": "q1_boundary_model_cv.csv",
        "boundary_endpoint_comparison": "q1_boundary_endpoint_comparison.csv",
    },
    "q2": {
        "workbook": "result2.xlsx",
        "result_data": "q2_result_data.json",
        "full_precision": "q2_result_full_precision.npz",
        "validation": "q2_validation.json",
        "parameter_sensitivity": "q2_parameter_sensitivity.json",
        "validation_export": "q2_validation_export.json",
    },
    "q3": {
        "workbook": "result3.xlsx",
        "result_data": "q3_result_data.json",
        "full_precision": "q3_result_full_precision.npz",
        "validation": "q3_validation.json",
        "validation_export": "q3_validation_export.json",
    },
    "q4": {
        "workbook": "result4.xlsx",
        "result_data": "q4_result_data.json",
        "full_precision": "q4_result_full_precision.npz",
        "validation": "q4_validation.json",
        "validation_export": "q4_validation_export.json",
        "radius_method_comparison": "q4_radius_method_comparison.csv",
    },
}


FIGURE_NAMES = {
    "q1": {
        "boundary_raw": "q1_fig_01_boundary_raw_scatter.png",
        "boundary_fit": "q1_fig_02_boundary_stretched_exp_fit.png",
        "temperature_moisture_field": "q1_fig_03_temperature_moisture_field.png",
    },
    "q2": {
        "boundary_stability": "q2_fig_01_boundary_stability_detection.png",
        "boundary_staged_fit": "q2_fig_02_staged_boundary_fit.png",
        "parameter_sensitivity": "q2_fig_03_parameter_sensitivity.png",
        "temperature_moisture_field": "q2_fig_04_temperature_moisture_field.png",
    },
    "q3": {
        "drying_result": "q3_fig_01_drying_result.png",
    },
    "q4": {
        "radius_raw": "q4_fig_01_radius_raw_scatter.png",
        "radius_pchip_fit": "q4_fig_02_radius_pchip_fit.png",
        "shrinkage_moisture_field": "q4_fig_03_shrinkage_moisture_field.png",
    },
}


GLOBAL_ARTIFACT_NAMES = {
    "reproducibility_check": "reproducibility_check.json",
}


def artifact_name(question: str, key: str) -> str:
    """Return the canonical filename for a question-level artifact."""
    try:
        return ARTIFACT_NAMES[question][key]
    except KeyError as exc:
        raise KeyError(f"Unknown artifact name: {question}/{key}") from exc


def workbook_path(results_root: Path, question: str) -> Path:
    """Return the package-level path for a result workbook."""
    return results_root / artifact_name(question, "workbook")


def figure_name(question: str, key: str) -> str:
    """Return the canonical filename for a generated figure."""
    try:
        return FIGURE_NAMES[question][key]
    except KeyError as exc:
        raise KeyError(f"Unknown figure name: {question}/{key}") from exc


def global_artifact_name(key: str) -> str:
    """Return the canonical filename for a package-level artifact."""
    try:
        return GLOBAL_ARTIFACT_NAMES[key]
    except KeyError as exc:
        raise KeyError(f"Unknown global artifact name: {key}") from exc
